# Generated by Django 3.2 on 2022-11-20 08:28

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('user', models.CharField(max_length=50, verbose_name='投稿者')),
                ('attached_image', models.ImageField(upload_to='attached_images', verbose_name='添付画像')),
                ('like', models.IntegerField(verbose_name='いいね')),
                ('read', models.IntegerField(verbose_name='既読者数')),
                ('read_text', models.IntegerField(verbose_name='既読ユーザー')),
            ],
        ),
    ]
