# Generated by Django 3.2 on 2022-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_text',
            field=models.TextField(verbose_name='既読ユーザー'),
        ),
    ]
