# Generated by Django 3.2 on 2022-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_read_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(null=True, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(null=True, verbose_name='既読者数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_text',
            field=models.TextField(null=True, verbose_name='既読ユーザー'),
        ),
    ]
